server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mobili_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# application.yml
mobili:
  security:
    jwt:
      secret-key: ${JWT_SECRET:7a44cf8b6e3f4b5a8d9e2c1b5a8d9e2c1b5a8d9e2c1b5a8d9e2c1b5a8d}
  backend:
    upload:
      root-directory: uploads
      users: users
      partners: partners
      vehicles: vehicles
